micronaut:
  application:
    name: complete
greeting:
  stem: Hello
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://nuc4010.fritz.box:5432/cmcdb`}
    username: ${JDBC_USER:cmcuser}
    password: ${JDBC_PASSWORD:cmcCoIn}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut.domain'
      - 'example.micronaut.wallet.impl.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false